// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvs7sQMZPAXbXPdlsVeqhJom9OUk9OqWE',
    appId: '1:79559555161:web:ced078c0baa0ff07581948',
    messagingSenderId: '79559555161',
    projectId: 'readingstats-flutter',
    authDomain: 'readingstats-flutter.firebaseapp.com',
    storageBucket: 'readingstats-flutter.firebasestorage.app',
    measurementId: 'G-ETEJZKRGNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARuGKzr9ULq6yNAT8xbOJFhxrWjH4vvmc',
    appId: '1:79559555161:android:b5496d8d9e129e18581948',
    messagingSenderId: '79559555161',
    projectId: 'readingstats-flutter',
    storageBucket: 'readingstats-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3GJeLob0YlbSngwPySMf9Q6gvR9ycyEc',
    appId: '1:79559555161:ios:1d8d2aa3ee4681db581948',
    messagingSenderId: '79559555161',
    projectId: 'readingstats-flutter',
    storageBucket: 'readingstats-flutter.firebasestorage.app',
    iosBundleId: 'com.example.readingstatsFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3GJeLob0YlbSngwPySMf9Q6gvR9ycyEc',
    appId: '1:79559555161:ios:1d8d2aa3ee4681db581948',
    messagingSenderId: '79559555161',
    projectId: 'readingstats-flutter',
    storageBucket: 'readingstats-flutter.firebasestorage.app',
    iosBundleId: 'com.example.readingstatsFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvs7sQMZPAXbXPdlsVeqhJom9OUk9OqWE',
    appId: '1:79559555161:web:7b7b67c7573bfcf6581948',
    messagingSenderId: '79559555161',
    projectId: 'readingstats-flutter',
    authDomain: 'readingstats-flutter.firebaseapp.com',
    storageBucket: 'readingstats-flutter.firebasestorage.app',
    measurementId: 'G-V4DQQGCTFD',
  );
}
